enableRobotsTXT = true
baseURL = "https://hitszjla.club/"
title = "HITsz日语社"
theme = "PaperMod"
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = false
[languages]
	[languages.zh-cn]
		languageName = "中文"
		weight = 1
timeZone = "Asia/Tokyo"
[params]
	defaultTheme = "auto"
	disableThemeToggle = false
	ShowReadingTime = false
	description = "日本文化 × 言语"
	customCSS = ["/css/custom.css"]
	ShowPostNavLinks = true
	ShowCodeCopyButtons = true
	ShowFooter = true
	[params.label]
		text = "HITSZ日语社"
	[params.footer]





[params.homeInfoParams]
	Title = "🌸 ようこそ！HITSZ日语社へ"
	Content = "ここでは私たちの活動・イベント・文化を紹介します。"

[menu]
	[[menu.main]]
		name = "关于&加入"
		url = "about/"
		weight = 10
	[[menu.main]]
		name = "公告"
		url = "news/"
		weight = 20
	[[menu.main]]
		name = "活动"
		url = "events/"
		weight = 30
	[[menu.main]]
		name = "留言&投稿"
		url = "participate/"
		weight = 40
	[[menu.main]]
		name = "每周一曲"
		url = "lyrics/"
		weight = 50
	[[menu.main]]
		name = "每周一文"
		url = "readings/"
		weight = 60
	[[menu.main]]
		name = "每周文法"
		url = "grammar/"
		weight = 70
	[[menu.main]]
		identifier = "search"
		name = "搜索内容"
		url = "search/"
		weight = 80
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
home = [ "HTML", "RSS", "JSON", "SearchData" ]

[outputFormats.SearchData]
mediaType = "application/json"
baseName = "search-data"
isPlainText = true
notAlternative = true
