baseURL = "http://jpa.guramod.club/"
title = "HITsz日语社"
theme = "PaperMod"
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = false
[languages] 
	[languages.zh-cn]
		languageName = "中文"
		weight = 1
timeZone = "Asia/Tokyo" 
[params]
	defaultTheme = "auto"
	disableThemeToggle = false
	ShowReadingTime = false 
	description = "日本文化 × 言语"
	customCSS = ["/css/custom.css"]
	ShowPostNavLinks = true
	ShowCodeCopyButtons = true
	ShowFooter = true
	[params.footer]
  		




[params.homeInfoParams]
	Title = "🌸 ようこそ！HITSZ日语社へ"
	Content = "ここでは私たちの活動・イベント・文化を紹介します。"

[menu] 
	[[menu.main]]
		name = "关于我们"
		url = "about"
	[[menu.main]]
		name = "活动"
		url = "events"
	[[menu.main]]
		name = "公告"
		url = "news"
	[[menu.main]]
		name = "加入我们"
		url = "join/join"
	[[menu.main]]
		name = "搜索"
		url = "search"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]
