# Generated by Django 5.2.17 on 2026-09-29 11:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateBucket',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField(editable=False, unique=True)),
                ('payload_hash', models.CharField(editable=False, max_length=64)),
                ('kind', models.CharField(choices=[('feedback', '匿名留言'), ('song', '每周一曲投稿')], max_length=12, verbose_name='类型')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('hidden', '已下架')], db_index=True, default='pending', max_length=12, verbose_name='审核状态')),
                ('category', models.CharField(blank=True, choices=[('activity', '活动心愿'), ('suggestion', '社团建议'), ('other', '其他留言')], max_length=16, verbose_name='留言分类')),
                ('nickname', models.CharField(blank=True, max_length=30, verbose_name='自愿署名')),
                ('body', models.TextField(max_length=2000, verbose_name='留言 / 推荐理由')),
                ('song_title', models.CharField(blank=True, max_length=150, verbose_name='歌曲名称')),
                ('artist', models.CharField(blank=True, max_length=100, verbose_name='歌手 / 演奏者')),
                ('music_url', models.URLField(blank=True, max_length=500, verbose_name='试听链接')),
                ('selected', models.BooleanField(default=False, verbose_name='已选为每周一曲')),
                ('public_reply', models.TextField(blank=True, max_length=2000, verbose_name='公开回复')),
                ('internal_note', models.TextField(blank=True, max_length=4000, verbose_name='内部备注（不公开）')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '投稿',
                'verbose_name_plural': '留言与歌曲投稿',
                'ordering': ['-created_at'],
                'permissions': [('moderate_submission', '可以审核、回复和下架投稿')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sending', '发送中'), ('sent', '已发送'), ('failed', '发送失败')], default='pending', max_length=12, verbose_name='通知状态')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='尝试次数')),
                ('next_attempt_at', models.DateTimeField(db_index=True, verbose_name='下次尝试时间')),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('last_error', models.CharField(blank=True, max_length=120, verbose_name='错误类型')),
                ('delivery_mode', models.CharField(blank=True, max_length=12, verbose_name='发送方式')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='submissions.submission', verbose_name='投稿')),
            ],
            options={
                'verbose_name': '邮件通知',
                'verbose_name_plural': '邮件通知',
            },
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=12, verbose_name='原状态')),
                ('new_status', models.CharField(max_length=12, verbose_name='新状态')),
                ('action', models.CharField(max_length=60, verbose_name='操作')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='管理员')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submissions.submission', verbose_name='投稿')),
            ],
            options={
                'verbose_name': '审核记录',
                'verbose_name_plural': '审核记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['kind', 'status', '-created_at'], name='submissions_kind_06249e_idx'),
        ),
    ]
